name = "IsoFuns"
uuid = "8ffeb364-5e46-4a19-b908-271cdb64df64"
authors = ["yutomiyatake <miyatake@cas.cmc.osaka-u.ac.jp> and contributors"]
version = "1.0.0-DEV"

[deps]
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
